version: '2.1'

services:
  nlp-api:
    build:
      context: ./nlp-api
      dockerfile: ./Dockerfile
    ports:
      - 9000
  emotion-api:
    build:
      context: ./crypto-emotion-api
      dockerfile: ./Dockerfile
    links:
      - nlp-api:nlp-api
    ports:
      - 3000:3000