const COINMARKET_API_URL = 'https://api.coinmarketcap.com/v1/ticker/';
const EMOTIONS_API_URL = 'http://35.176.189.136:3000';

function scriptToGetCharts() {
  var charts = {};
  var coins = $('#currencies').find('tr');

  for (var i = 1; i < coins.length; i++) {
    var id = coins[i].id.replace('id-', '');
    var td = $('#id-' + id);
    charts[id] = td.find('img')[0].src;
  }
  return charts;
}

const ACCEPTED_COINS = [
  'btc',
  'eth',
  'ltc',
  'neo',
  'omg',
  'req',
  'elix',
  'wtc',
  'ark',
  'omg',
  'xrp',
  'dash',
  'xem',
  'xmr',
  'miota',
  'gnt',
];

const COIN_CHARTS = {
  '0x': 'https://files.coinmarketcap.com/generated/sparklines/1896.png',
  'adx-net': 'https://files.coinmarketcap.com/generated/sparklines/1768.png',
  aeternity: 'https://files.coinmarketcap.com/generated/sparklines/1700.png',
  ardor: 'https://files.coinmarketcap.com/generated/sparklines/1320.png',
  ark: 'https://files.coinmarketcap.com/generated/sparklines/1586.png',
  'attention-token-of-media': 'https://files.coinmarketcap.com/generated/sparklines/2015.png',
  augur: 'https://files.coinmarketcap.com/generated/sparklines/1104.png',
  b3coin: 'https://files.coinmarketcap.com/generated/sparklines/1371.png',
  bancor: 'https://files.coinmarketcap.com/generated/sparklines/1727.png',
  'basic-attention-token': 'https://files.coinmarketcap.com/generated/sparklines/1697.png',
  'binance-coin': 'https://files.coinmarketcap.com/generated/sparklines/1839.png',
  bitcoin: 'https://files.coinmarketcap.com/generated/sparklines/1.png',
  'bitcoin-cash': 'https://files.coinmarketcap.com/generated/sparklines/1831.png',
  bitcoindark: 'https://files.coinmarketcap.com/generated/sparklines/467.png',
  bitconnect: 'https://files.coinmarketcap.com/generated/sparklines/1513.png',
  bitquence: 'https://files.coinmarketcap.com/generated/sparklines/1817.png',
  bitshares: 'https://files.coinmarketcap.com/generated/sparklines/463.png',
  blocknet: 'https://files.coinmarketcap.com/generated/sparklines/707.png',
  byteball: 'https://files.coinmarketcap.com/generated/sparklines/1492.png',
  'bytecoin-bcn': 'https://files.coinmarketcap.com/generated/sparklines/372.png',
  bytom: 'https://files.coinmarketcap.com/generated/sparklines/1866.png',
  cardano: 'https://files.coinmarketcap.com/generated/sparklines/2010.png',
  chainlink: 'https://files.coinmarketcap.com/generated/sparklines/1975.png',
  civic: 'https://files.coinmarketcap.com/generated/sparklines/1816.png',
  cryptonex: 'https://files.coinmarketcap.com/generated/sparklines/2027.png',
  dash: 'https://files.coinmarketcap.com/generated/sparklines/131.png',
  decred: 'https://files.coinmarketcap.com/generated/sparklines/1168.png',
  digibyte: 'https://files.coinmarketcap.com/generated/sparklines/109.png',
  digixdao: 'https://files.coinmarketcap.com/generated/sparklines/1229.png',
  dogecoin: 'https://files.coinmarketcap.com/generated/sparklines/74.png',
  edgeless: 'https://files.coinmarketcap.com/generated/sparklines/1596.png',
  electroneum: 'https://files.coinmarketcap.com/generated/sparklines/2137.png',
  eos: 'https://files.coinmarketcap.com/generated/sparklines/1765.png',
  ethereum: 'https://files.coinmarketcap.com/generated/sparklines/1027.png',
  'ethereum-classic': 'https://files.coinmarketcap.com/generated/sparklines/1321.png',
  factom: 'https://files.coinmarketcap.com/generated/sparklines/1087.png',
  faircoin: 'https://files.coinmarketcap.com/generated/sparklines/224.png',
  funfair: 'https://files.coinmarketcap.com/generated/sparklines/1757.png',
  gamecredits: 'https://files.coinmarketcap.com/generated/sparklines/576.png',
  gas: 'https://files.coinmarketcap.com/generated/sparklines/1785.png',
  'gnosis-gno': 'https://files.coinmarketcap.com/generated/sparklines/1659.png',
  'golem-network-tokens': 'https://files.coinmarketcap.com/generated/sparklines/1455.png',
  groestlcoin: 'https://files.coinmarketcap.com/generated/sparklines/258.png',
  gxshares: 'https://files.coinmarketcap.com/generated/sparklines/1750.png',
  hshare: 'https://files.coinmarketcap.com/generated/sparklines/1903.png',
  iconomi: 'https://files.coinmarketcap.com/generated/sparklines/1408.png',
  iota: 'https://files.coinmarketcap.com/generated/sparklines/1720.png',
  komodo: 'https://files.coinmarketcap.com/generated/sparklines/1521.png',
  kucoin: 'https://files.coinmarketcap.com/generated/sparklines/2087.png',
  'kyber-network': 'https://files.coinmarketcap.com/generated/sparklines/1982.png',
  lisk: 'https://files.coinmarketcap.com/generated/sparklines/1214.png',
  litecoin: 'https://files.coinmarketcap.com/generated/sparklines/2.png',
  loopring: 'https://files.coinmarketcap.com/generated/sparklines/1934.png',
  lykke: 'https://files.coinmarketcap.com/generated/sparklines/1454.png',
  maidsafecoin: 'https://files.coinmarketcap.com/generated/sparklines/291.png',
  mcap: 'https://files.coinmarketcap.com/generated/sparklines/1690.png',
  metal: 'https://files.coinmarketcap.com/generated/sparklines/1788.png',
  metaverse: 'https://files.coinmarketcap.com/generated/sparklines/1703.png',
  monaco: 'https://files.coinmarketcap.com/generated/sparklines/1776.png',
  monacoin: 'https://files.coinmarketcap.com/generated/sparklines/213.png',
  monero: 'https://files.coinmarketcap.com/generated/sparklines/328.png',
  'nav-coin': 'https://files.coinmarketcap.com/generated/sparklines/377.png',
  neblio: 'https://files.coinmarketcap.com/generated/sparklines/1955.png',
  nem: 'https://files.coinmarketcap.com/generated/sparklines/873.png',
  neo: 'https://files.coinmarketcap.com/generated/sparklines/1376.png',
  nexus: 'https://files.coinmarketcap.com/generated/sparklines/789.png',
  nxt: 'https://files.coinmarketcap.com/generated/sparklines/66.png',
  omisego: 'https://files.coinmarketcap.com/generated/sparklines/1808.png',
  particl: 'https://files.coinmarketcap.com/generated/sparklines/1826.png',
  pivx: 'https://files.coinmarketcap.com/generated/sparklines/1169.png',
  populous: 'https://files.coinmarketcap.com/generated/sparklines/1789.png',
  'power-ledger': 'https://files.coinmarketcap.com/generated/sparklines/2132.png',
  pura: 'https://files.coinmarketcap.com/generated/sparklines/870.png',
  qtum: 'https://files.coinmarketcap.com/generated/sparklines/1684.png',
  'ripio-credit-network': 'https://files.coinmarketcap.com/generated/sparklines/2096.png',
  ripple: 'https://files.coinmarketcap.com/generated/sparklines/52.png',
  salt: 'https://files.coinmarketcap.com/generated/sparklines/1996.png',
  siacoin: 'https://files.coinmarketcap.com/generated/sparklines/1042.png',
  singulardtv: 'https://files.coinmarketcap.com/generated/sparklines/1409.png',
  status: 'https://files.coinmarketcap.com/generated/sparklines/1759.png',
  steem: 'https://files.coinmarketcap.com/generated/sparklines/1230.png',
  stellar: 'https://files.coinmarketcap.com/generated/sparklines/512.png',
  storj: 'https://files.coinmarketcap.com/generated/sparklines/1772.png',
  stratis: 'https://files.coinmarketcap.com/generated/sparklines/1343.png',
  'streamr-datacoin': 'https://files.coinmarketcap.com/generated/sparklines/2143.png',
  syscoin: 'https://files.coinmarketcap.com/generated/sparklines/541.png',
  tenx: 'https://files.coinmarketcap.com/generated/sparklines/1758.png',
  tether: 'https://files.coinmarketcap.com/generated/sparklines/825.png',
  tron: 'https://files.coinmarketcap.com/generated/sparklines/1958.png',
  ubiq: 'https://files.coinmarketcap.com/generated/sparklines/588.png',
  vechain: 'https://files.coinmarketcap.com/generated/sparklines/1904.png',
  verge: 'https://files.coinmarketcap.com/generated/sparklines/693.png',
  veritaseum: 'https://files.coinmarketcap.com/generated/sparklines/1710.png',
  vertcoin: 'https://files.coinmarketcap.com/generated/sparklines/99.png',
  walton: 'https://files.coinmarketcap.com/generated/sparklines/1925.png',
  waves: 'https://files.coinmarketcap.com/generated/sparklines/1274.png',
  zcash: 'https://files.coinmarketcap.com/generated/sparklines/1437.png',
  zcoin: 'https://files.coinmarketcap.com/generated/sparklines/1414.png',
  zencash: 'https://files.coinmarketcap.com/generated/sparklines/1698.png',
  zeusshield: 'https://files.coinmarketcap.com/generated/sparklines/2047.png',
  'request-network': 'https://files.coinmarketcap.com/generated/sparklines/2071.png',
  elixir: 'https://files.coinmarketcap.com/generated/sparklines/1980.png',
}

const IMAGE_EMOTION = [
  {
    name: 'buy',
    sadness: 0.7,
    joy: 0.7,
    anger: 0.2,
    disgust: 0.7,
    fear: 0.3,
    sentimentScore: 4,
  },
  {
    name: 'dump',
    sadness: 0.3,
    joy: 0.5,
    anger: 0.5,
    disgust: 0.5,
    fear: 0.4,
    sentimentScore: 4,
  },
  {
    name: 'fuder',
    sadness: 0.6,
    joy: 0.4,
    anger: 0.6,
    disgust: 0.6,
    fear: 0.6,
    sentimentScore: 5,
  },
  {
    name: 'going-down',
    sadness: 0.6,
    joy: 0.4,
    anger: 0.6,
    disgust: 0.6,
    fear: 0.6,
    sentimentScore: 4,
  },
  {
    name: 'going-up',
    sadness: 0.1,
    joy: 0.7,
    anger: 0.1,
    disgust: 0.1,
    fear: 0.0,
    sentimentScore: 7,
  },
  {
    name: 'hodl',
    sadness: 0.6,
    joy: 0.4,
    anger: 0.4,
    disgust: 0.4,
    fear: 0.6,
    sentimentScore: 4,
  },
  {
    name: 'ok',
    sadness: 0.3,
    joy: 0.5,
    anger: 0.3,
    disgust: 0.3,
    fear: 0.1,
    sentimentScore: 6,
  },
  {
    name: 'pump',
    sadness: 0.3,
    joy: 0.7,
    anger: 0.3,
    disgust: 0.3,
    fear: 0.2,
    sentimentScore: 6,
  },
  {
    name: 'reqt',
    sadness: 0.8,
    joy: 0.2,
    anger: 0.6,
    disgust: 0.6,
    fear: 0.6,
    sentimentScore: 2,
  },
  {
    name: 'rich',
    sadness: 0.1,
    joy: 0.8,
    anger: 0.1,
    disgust: 0.1,
    fear: 0.0,
    sentimentScore: 8,
  },
  {
    name: 'to-the-moon',
    sadness: 0.2,
    joy: 0.6,
    anger: 0.2,
    disgust: 0.2,
    fear: 0.2,
    sentimentScore: 6,
  },
];

export { ACCEPTED_COINS, COINMARKET_API_URL, COIN_CHARTS, EMOTIONS_API_URL, IMAGE_EMOTION };
