source 'http://rubygems.org'

ruby '2.3.1'

gem 'grape', '~> 0.16'
gem 'grape-entity'
gem 'grape-swagger'
gem 'grape-swagger-entity'
gem 'json'
gem 'newrelic_rpm'
gem 'rack-cors'
gem 'mime-types'
gem 'nokogiri'
gem 'redd'
gem 'pry'
gem 'rest-client'
gem 'websocket-rack'
gem 'faye-websocket'
gem 'faye'

group :development do
  gem 'rake'
  gem 'guard'
  gem 'guard-bundler'
  gem 'guard-rack'
  gem 'rubocop'
end

group :test do
  gem 'rspec'
  gem 'rack-test'
  gem 'capybara'
  gem 'selenium-webdriver'
end
